# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestAlamofire' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestAlamofire
  pod 'Alamofire', '~> 4.7'

  target 'TestAlamofireTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestAlamofireUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
